# Generated by Django 2.0.7 on 2018-09-22 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='posts', verbose_name='Основное изображение')),
            ],
            options={
                'ordering': ['-post_datetime'],
            },
        ),
    ]
