# Generated by Django 2.1.3 on 2018-11-08 08:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('preview_text', models.CharField(max_length=200, verbose_name='Текст для превью')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='posts', verbose_name='Основное изображение')),
                ('video_code_url', models.URLField(blank=True)),
            ],
            options={
                'permissions': (('create_post', 'Может создать пост'), ('edit_post', 'Может изменить пост'), ('drop_post', 'Может удалить пост'), ('moderate_post', 'Может модерировать пост')),
                'ordering': ['-post_datetime'],
            },
        ),
    ]
