# Generated by Django 2.0.7 on 2018-09-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_datetime'], 'permissions': (('create_post', 'Может создать пост'), ('edit_post', 'Может изменить пост'), ('drop_post', 'Может удалить пост'), ('moderate_post', 'Может модерировать пост'))},
        ),
    ]
