# Generated by Django 2.0.7 on 2018-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180923_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(default='Максимум 200 символов', max_length=200, verbose_name='Текст для превью'),
        ),
    ]
