# Generated by Django 2.0.7 on 2018-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_preview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.CharField(max_length=200, verbose_name='Текст для превью'),
        ),
    ]
