# Generated by Django 2.0.7 on 2018-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180925_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_code',
            field=models.TextField(blank=True),
        ),
    ]
