# Generated by Django 2.0.7 on 2018-09-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post_video_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_code',
        ),
    ]
